version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: inventory_management_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: inventory_management_root
      POSTGRES_PASSWORD: inventory_management_password
      POSTGRES_DB: inventory_management_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
